// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userInfo.proto

package com.yann.em.grpc.UserInfo;

public interface UserInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string sex = 3;</code>
   */
  java.lang.String getSex();
  /**
   * <code>string sex = 3;</code>
   */
  com.google.protobuf.ByteString
      getSexBytes();

  /**
   * <code>string addr = 4;</code>
   */
  java.lang.String getAddr();
  /**
   * <code>string addr = 4;</code>
   */
  com.google.protobuf.ByteString
      getAddrBytes();
}
