// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userInfo.proto

package com.yann.em.grpc.UserInfo;

public final class UserInfoOuterClass {
  private UserInfoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserStr_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserStr_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserInfoReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserInfoReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserInfoResponse_Data_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserInfoResponse_Data_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016userInfo.proto\"\026\n\007UserStr\022\013\n\003str\030\001 \001(\t" +
      "\"\'\n\013UserInfoReq\022\014\n\004name\030\001 \001(\t\022\n\n\002id\030\002 \001(" +
      "\003\"\211\001\n\020UserInfoResponse\022\014\n\004code\030\001 \001(\005\022\013\n\003" +
      "msg\030\002 \001(\t\022\017\n\007success\030\003 \001(\010\022$\n\004data\030\004 \001(\013" +
      "2\026.UserInfoResponse.Data\032#\n\004Data\022\033\n\010user" +
      "Info\030\001 \001(\0132\t.UserInfo\"?\n\010UserInfo\022\n\n\002id\030" +
      "\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\013\n\003sex\030\003 \001(\t\022\014\n\004addr" +
      "\030\004 \001(\t2\242\001\n\017UserInfoService\0222\n\rqueryUserI" +
      "nfo\022\014.UserInfoReq\032\021.UserInfoResponse\"\000\0223" +
      "\n\016queryUserInfo2\022\014.UserInfoReq\032\021.UserInf" +
      "oResponse\"\000\022&\n\016queryUserInfo3\022\010.UserStr\032" +
      "\010.UserStr\"\000B\035\n\031com.yann.em.grpc.UserInfo" +
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_UserStr_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserStr_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserStr_descriptor,
        new java.lang.String[] { "Str", });
    internal_static_UserInfoReq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UserInfoReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserInfoReq_descriptor,
        new java.lang.String[] { "Name", "Id", });
    internal_static_UserInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_UserInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserInfoResponse_descriptor,
        new java.lang.String[] { "Code", "Msg", "Success", "Data", });
    internal_static_UserInfoResponse_Data_descriptor =
      internal_static_UserInfoResponse_descriptor.getNestedTypes().get(0);
    internal_static_UserInfoResponse_Data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserInfoResponse_Data_descriptor,
        new java.lang.String[] { "UserInfo", });
    internal_static_UserInfo_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_UserInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserInfo_descriptor,
        new java.lang.String[] { "Id", "Name", "Sex", "Addr", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
