// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userInfo.proto

package com.yann.em.grpc.UserInfo;

public interface UserStrOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserStr)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string str = 1;</code>
   */
  java.lang.String getStr();
  /**
   * <code>string str = 1;</code>
   */
  com.google.protobuf.ByteString
      getStrBytes();
}
